services:
    order-system:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT}:8080"
        environment:
            - DB_HOST=host.docker.internal
            - PGSQL_HOST=host.docker.internal
            - REDIS_HOST=host.docker.internal
        depends_on:
            - postgres
            - redis
    postgres:
        image: postgres:16
        ports:
            - "${PGSQL_PORT}:5432"
        environment:
            POSTGRES_DB: ${PGSQL_DATABASE}
            POSTGRES_USER: ${PGSQL_USERNAME}
            POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
        volumes:
            - order-system-db-postgres:/var/lib/postgresql/data
    redis:
        image: redis:7.2
        platform: linux/arm64
        ports:
            - "${REDIS_PORT}:6379"

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.16.100.0/24

volumes:
    order-system-db-postgres:
